name: DNS Sync to Cloudflare

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'requests/**.json'
      - 'domains/available_domains.json'
  workflow_dispatch: # Allows manual triggering

jobs:
  sync-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sync DNS records to Cloudflare
        run: python .github/scripts/cloudflare_manager.py
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CONFIG_FILE: 'config.json'
          DOMAINS_FILE: 'domains/available_domains.json'
          REQUESTS_DIR: 'requests'
