name: 每日健康检查

on:
  schedule:
    # 每天 UTC 时间 02:00 执行（北京时间 10:00）
    - cron: '0 2 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  health-check:
    name: DNS 健康检查
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 运行健康检查
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        python scripts/health_check.py --report-file health_report.md
    
    - name: 上传健康报告
      uses: actions/upload-artifact@v3
      with:
        name: health-report
        path: health_report.md
    
    - name: 创建 Issue（如果检查失败）
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          let reportContent = '';
          
          try {
            reportContent = fs.readFileSync('health_report.md', 'utf8');
          } catch (error) {
            reportContent = '健康检查报告生成失败';
          }
          
          const title = `🚨 DNS 健康检查失败 - ${new Date().toLocaleDateString('zh-CN')}`;
          const body = `## 健康检查失败\n\n${reportContent}\n\n请检查 DNS 记录和 Cloudflare 配置。\n\n> 此 Issue 由自动健康检查生成`;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['health-check', 'bug']
          });
