name: Subdomain Deployment

on:
  pull_request:
    paths:
      - 'subdomains/*.json'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate JSON format
        run: |
          for file in subdomains/*.json; do
            jq empty "$file" || exit 1
          done

  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Cloudflare
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          for file in subdomains/*.json; do
            subdomain=$(basename "$file" .json)
            record=$(jq -r '.record' "$file")
            type=$(jq -r '.type' "$file")
            content=$(jq -r '.content' "$file")
            ttl=$(jq -r '.ttl' "$file")

            curl -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/dns_records" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: application/json" \
              --data '{
                "type": "'"$type"'",
                "name": "'"$subdomain"'",
                "content": "'"$content"'",
                "ttl": '"$ttl"'
              }'
          done