# GitHub Actions workflow for Subdomain Allocation Bot

name: Subdomain Allocation Bot

on:
  pull_request:
    types: [opened, edited, reopened]
  pull_request_target:
    types: [closed]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Validate PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: python bot.py

  apply:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Apply DNS records
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          python bot.py --apply --pr-number ${{ github.event.pull_request.number }}
