name: 子域名更新工作流程

on:
  pull_request:
    branches:
      - main
    paths:
      - 'subdomains/**'
  push:
    branches:
      - main
    paths:
      - 'subdomains/**'

jobs:
  validate-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 安装依赖
        run: npm ci

      - name: 验证 JSON 文件
        if: github.event_name == 'pull_request'
        run: |
          node scripts/validate-json.js ${{ github.event.pull_request.head.sha }}

      - name: 检查权限
        if: github.event_name == 'pull_request'
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          node scripts/check-permission.js ${{ github.event.pull_request.head.sha }}

      - name: 更新 DNS 记录
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          node scripts/update-dns.js

      - name: 通知管理员
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            
            github.rest.issues.createComment({
              owner,
              repo,
              issue_number: prNumber,
              body: '🔍 子域名申请已通过验证，等待管理员审核。'
            });

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: validate-and-update
    steps:
      - uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 安装依赖
        run: npm ci

      - name: 构建项目
        run: npm run build

      - name: 部署到 Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: libredomains
          directory: out