name: Subdomain Update Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'subdomains/**'

jobs:
  validate-and-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Validate JSON file
        run: |
          node scripts/validate-json.js ${{ github.event.pull_request.head.sha }}

      - name: Check Permission
        run: |
          node scripts/check-permission.js ${{ github.event.pull_request.head.sha }}

      - name: Notify Admin
        if: always()
        env:
          ADMIN_EMAIL: admin@example.com
        run: |
          echo "Sending notification to admin (${ADMIN_EMAIL})"

      - name: Update DNS Record
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          node scripts/update-dns.js