name: 验证域名申请

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'domains/**/*.json'

jobs:
  validate-domain:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: 安装依赖
        run: pip install requests dnspython
        
      - name: 获取更改的文件
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: 'domains/**/*.json'
          separator: ' '
      
      - name: 验证域名配置
        id: validate
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          mkdir -p /tmp/validation
          python scripts/bot/pr_checker.py --files ${{ steps.changed-files.outputs.all_changed_files }} --output /tmp/validation/result.md
          echo "status=$?" >> $GITHUB_OUTPUT
          
      - name: 发表评论
        uses: actions/github-script@v7
        if: steps.changed-files.outputs.all_changed_files != ''
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const result = fs.readFileSync('/tmp/validation/result.md', 'utf8');
            const valid = ${{ steps.validate.outputs.status }} === '0';
            
            const header = valid 
              ? '## ✅ 域名申请验证通过' 
              : '## ❌ 域名申请验证失败';
            
            const body = `${header}\n\n${result}\n\n> 这是自动验证消息，如有问题请联系管理员。`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
            
      - name: 验证结果
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          if [ "${{ steps.validate.outputs.status }}" != "0" ]; then
            echo "域名配置验证失败，请查看PR评论了解详情。"
            exit 1
          fi
