name: 验证域名申请

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'domains/**/*.json'

jobs:
  validate-domain:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pull-requests: read
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: 安装依赖
        run: pip install requests dnspython
        
      - name: 获取更改的文件
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: 'domains/**/*.json'
          separator: ' '
      
      - name: 验证域名配置
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          echo "=== 开始验证域名配置 ==="
          echo "更改的文件: ${{ steps.changed-files.outputs.all_changed_files }}"
          echo "PR作者: ${{ github.event.pull_request.user.login }}"
          echo ""
          
          # 运行验证脚本并直接输出到控制台，包含所有权验证
          if python scripts/bot/pr_checker.py \
            --files ${{ steps.changed-files.outputs.all_changed_files }} \
            --pr-author "${{ github.event.pull_request.user.login }}" \
            --repo-owner "${{ github.repository_owner }}" \
            --repo-name "${{ github.event.repository.name }}" \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --debug; then
            echo ""
            echo "🎉 所有域名配置验证通过！"
          else
            echo ""
            echo "❌ 域名配置验证失败，请查看上方的详细错误信息。"
            exit 1
          fi
      
      - name: 无文件更改
        if: steps.changed-files.outputs.all_changed_files == ''
        run: |
          echo "ℹ️ 没有检测到域名配置文件的更改。"
